# Simple workflow for deploying static content to GitHub Pages
name: Create index

on:
  push:
    branches: main
    
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create index file
        run: Rscript -e 'source("create_index.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -am "Index updated"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions